# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170116_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='like',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='view',
            new_name='views',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='view',
            new_name='views',
        ),
    ]
